In [25]:
import pickle 
import numpy as np

In [26]:
ohe_sex_embarked=pickle.load(open("ohe_sex_embarked.pkl","rb"))
clf=pickle.load(open("clf.pkl","rb"))

In [27]:
new_input=np.array([1,"male",35,2,4,300,"S"],dtype=object).reshape(1,7)

In [28]:
test_input_sex_embarked=ohe_sex_embarked.transform(new_input[:,[1,-1]].reshape(1,2))

D:\jupyterlab\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [29]:
test_input_sex_embarked

array([[0., 1., 0., 0., 1.]])

In [30]:
test_input_age=new_input[:,2].reshape(1,1)

In [31]:
test_input_age

array([[35]], dtype=object)

In [32]:
new_input_transformed=np.concatenate((new_input[:,[0,3,4,5]],test_input_sex_embarked,test_input_age),axis=1)

In [33]:
new_input_transformed.shape

(1, 10)

In [34]:
clf.predict(new_input_transformed)

array([0])

In [35]:
import pandas as pd

In [36]:
pd.DataFrame(new_input_transformed)

0  1  2    3    4    5    6    7    8   9
0  1  2  4  300  0.0  1.0  0.0  0.0  1.0  35